/**
 * Named atlas tiles of the 0.10 block set. The first stages numbered their tiles by hand below
 * the item sprites; everything new lives in its own band above the animated strips, and is named
 * so the renderer paints it by meaning instead of by a bare number.
 */
export const EXTRA_TILE_BASE = 320;
/** The sixteen dye colours of wool and carpet, in the reference order. */
export const WOOL_COLORS = [
  ['white', 'Белая', 0xe9ecec],
  ['orange', 'Оранжевая', 0xf07613],
  ['magenta', 'Пурпурная', 0xbd44b3],
  ['light_blue', 'Голубая', 0x3aafd9],
  ['yellow', 'Жёлтая', 0xf8c627],
  ['lime', 'Лаймовая', 0x70b919],
  ['pink', 'Розовая', 0xed8dac],
  ['gray', 'Серая', 0x3e4447],
  ['light_gray', 'Светло-серая', 0x8e8e86],
  ['cyan', 'Бирюзовая', 0x158991],
  ['purple', 'Фиолетовая', 0x792aac],
  ['blue', 'Синяя', 0x35399d],
  ['brown', 'Коричневая', 0x724728],
  ['green', 'Зелёная', 0x546d1b],
  ['red', 'Красная', 0xa12722],
  ['black', 'Чёрная', 0x141519],
] as const;
/** Round H tiles, appended to the band so every older tile keeps its number. */
export const H_TILE_NAMES = [
  'emerald_ore',
  'emerald_block',
  'diamond_block',
  'coal_block',
  'redstone_block',
  'lapis_block',
  'bricks',
  'quartz_top',
  'quartz_side',
  'quartz_pillar_side',
  'quartz_pillar_top',
  'wool_white',
  'wool_orange',
  'wool_magenta',
  'wool_light_blue',
  'wool_yellow',
  'wool_lime',
  'wool_pink',
  'wool_gray',
  'wool_light_gray',
  'wool_cyan',
  'wool_purple',
  'wool_blue',
  'wool_brown',
  'wool_green',
  'wool_red',
  'wool_black',
  'iron_bars',
  'jack_o_lantern',
  'spruce_sapling',
  'birch_sapling',
  'jungle_sapling',
  'acacia_sapling',
  'dark_oak_sapling',
  'carrots_0',
  'carrots_1',
  'carrots_2',
  'carrots_3',
  'potatoes_0',
  'potatoes_1',
  'potatoes_2',
  'potatoes_3',
  'beetroots_0',
  'beetroots_1',
  'beetroots_2',
  'beetroots_3',
  'stem_0',
  'stem_1',
  'stem_2',
  'stem_3',
  'cake_top',
  'cake_side',
  'cake_inner',
  'cake_bottom',
  'ladder',
  'oak_trapdoor',
] as const;
export type HTileName = (typeof H_TILE_NAMES)[number];
export const EXTRA_TILE_NAMES = [
  'grass_snowy_side',
  'podzol_top',
  'podzol_side',
  'coarse_dirt',
  'red_sand',
  'clay',
  'terracotta',
  'terracotta_orange',
  'terracotta_yellow',
  'terracotta_white',
  'terracotta_light_gray',
  'terracotta_brown',
  'terracotta_red',
  'granite',
  'diorite',
  'andesite',
  'spruce_log',
  'spruce_log_top',
  'spruce_planks',
  'spruce_leaves',
  'birch_log_top',
  'birch_planks',
  'birch_leaves',
  'jungle_log',
  'jungle_log_top',
  'jungle_planks',
  'jungle_leaves',
  'acacia_log',
  'acacia_log_top',
  'acacia_planks',
  'acacia_leaves',
  'dark_oak_log',
  'dark_oak_log_top',
  'dark_oak_planks',
  'dark_oak_leaves',
  'fern',
  'dead_bush',
  'poppy',
  'blue_orchid',
  'allium',
  'red_tulip',
  'brown_mushroom',
  'red_mushroom',
  'lily_pad',
  'cobweb',
  'packed_ice',
  'mossy_stone_bricks',
  'cracked_stone_bricks',
  'chiseled_sandstone',
  'hay_side',
  'hay_top',
  'oak_door_lower',
  'oak_door_upper',
  'spruce_door_lower',
  'spruce_door_upper',
  'acacia_door_lower',
  'acacia_door_upper',
  'mycelium_top',
  'mycelium_side',
  'stone_slab_side',
  'stone_slab_top',
  'stone_bricks',
  'snow',
  'sandstone_side',
  'sandstone_top',
  'sandstone_bottom',
  'double_tall_grass',
  'sunflower',
  'snowy_leaves',
  'ice',
  'gravel',
  'mossy_cobblestone',
  'mushroom_stem',
  'mushroom_pores',
  'brown_mushroom_cap',
  'red_mushroom_cap',
  'vine',
  ...H_TILE_NAMES,
] as const;
export type ExtraTileName = (typeof EXTRA_TILE_NAMES)[number];
export const TILE = Object.freeze(
  Object.fromEntries(EXTRA_TILE_NAMES.map((name, index) => [name, EXTRA_TILE_BASE + index])),
) as Readonly<Record<ExtraTileName, number>>;
export function extraTileName(tile: number): ExtraTileName | undefined {
  return EXTRA_TILE_NAMES[tile - EXTRA_TILE_BASE];
}
