/**
 * Pixel icons of the 0.10 interface, drawn on a 12×12 grid: `x` is the current colour, `o` the
 * same at half strength. Rendered as crisp SVG rects, so they stay sharp at any size and follow
 * `color` like text. Sizes snap to whole pixels of the grid (12, 18, 24, 36).
 */
const GRIDS: Record<string, string[]> = {
  play: [
    '............',
    '.xx.........',
    '.xxxx.......',
    '.xxxxxx.....',
    '.xxxxxxxx...',
    '.xxxxxxxxxx.',
    '.xxxxxxxxxx.',
    '.xxxxxxxx...',
    '.xxxxxx.....',
    '.xxxx.......',
    '.xx.........',
    '............',
  ],
  pause: [
    '............',
    '..xxx..xxx..',
    '..xxx..xxx..',
    '..xxx..xxx..',
    '..xxx..xxx..',
    '..xxx..xxx..',
    '..xxx..xxx..',
    '..xxx..xxx..',
    '..xxx..xxx..',
    '..xxx..xxx..',
    '..xxx..xxx..',
    '............',
  ],
  arrow: [
    '............',
    '............',
    '.......x....',
    '.......xx...',
    '.......xxx..',
    '.xxxxxxxxxx.',
    '.xxxxxxxxxx.',
    '.......xxx..',
    '.......xx...',
    '.......x....',
    '............',
    '............',
  ],
  back: [
    '............',
    '............',
    '....x.......',
    '...xx.......',
    '..xxx.......',
    '.xxxxxxxxxx.',
    '.xxxxxxxxxx.',
    '..xxx.......',
    '...xx.......',
    '....x.......',
    '............',
    '............',
  ],
  close: [
    '............',
    '.xx......xx.',
    '.xxx....xxx.',
    '..xxx..xxx..',
    '...xxxxxx...',
    '....xxxx....',
    '....xxxx....',
    '...xxxxxx...',
    '..xxx..xxx..',
    '.xxx....xxx.',
    '.xx......xx.',
    '............',
  ],
  settings: [
    '.....xx.....',
    '..x.xxxx.x..',
    '.xxxxxxxxxx.',
    '..xxxooxxx..',
    '.xxxo..oxxx.',
    'xxxo....oxxx',
    'xxxo....oxxx',
    '.xxxo..oxxx.',
    '..xxxooxxx..',
    '.xxxxxxxxxx.',
    '..x.xxxx.x..',
    '.....xx.....',
  ],
  folder: [
    '............',
    '.xxxx.......',
    '.xoooxx.....',
    '.xxxxxxxxxx.',
    '.xoooooooox.',
    '.xoooooooox.',
    '.xoooooooox.',
    '.xoooooooox.',
    '.xoooooooox.',
    '.xxxxxxxxxx.',
    '............',
    '............',
  ],
  save: [
    '.xxxxxxxxx..',
    '.x.xxxxx.xx.',
    '.x.xxxxx..x.',
    '.x.xx.xx..x.',
    '.x.xxxxx..x.',
    '.x........x.',
    '.x.oooooo.x.',
    '.x.o....o.x.',
    '.x.oooooo.x.',
    '.x.o....o.x.',
    '.xxxxxxxxxx.',
    '............',
  ],
  upload: [
    '.....xx.....',
    '....xxxx....',
    '...xxxxxx...',
    '..xx.xx.xx..',
    '.....xx.....',
    '.....xx.....',
    '.....xx.....',
    '............',
    '.x........x.',
    '.x........x.',
    '.xxxxxxxxxx.',
    '............',
  ],
  report: [
    '.....xx.....',
    '.....xx.....',
    '.....xx.....',
    '.....xx.....',
    '..xx.xx.xx..',
    '...xxxxxx...',
    '....xxxx....',
    '............',
    '.x........x.',
    '.x........x.',
    '.xxxxxxxxxx.',
    '............',
  ],
  copy: [
    '....xxxxxxx.',
    '....xoooooxx',
    '.xxxxxxxooxx',
    '.xoooooxooxx',
    '.xoooooxooxx',
    '.xoooooxooxx',
    '.xoooooxxxxx',
    '.xoooooxx...',
    '.xoooooxx...',
    '.xoooooxx...',
    '.xxxxxxxx...',
    '............',
  ],
  search: [
    '...xxxx.....',
    '..xooooxx...',
    '.xoo....x...',
    '.xo.....ox..',
    '.xo......x..',
    '.x.......x..',
    '..x.....x...',
    '..xx...xxx..',
    '....xxx.xxx.',
    '.........xxx',
    '..........xx',
    '............',
  ],
  trash: [
    '....xxxx....',
    '.xxxxxxxxxx.',
    '............',
    '..xxxxxxxx..',
    '..xoxoxoxx..',
    '..xoxoxoxx..',
    '..xoxoxoxx..',
    '..xoxoxoxx..',
    '..xoxoxoxx..',
    '..xxxxxxxx..',
    '............',
    '............',
  ],
  edit: [
    '........xx..',
    '.......xxxx.',
    '......xoxxx.',
    '.....xoxxx..',
    '....xoxxx...',
    '...xoxxx....',
    '..xoxxx.....',
    '.xxxxx......',
    '.xxxx.......',
    '.xx.........',
    '............',
    '............',
  ],
  shield: [
    '.xxxxxxxxxx.',
    '.x........x.',
    '.x.oooooo.x.',
    '.x.oooooo.x.',
    '.x.oooooo.x.',
    '.x.oooooo.x.',
    '..x.oooo.x..',
    '..x.oooo.x..',
    '...x.oo.x...',
    '....x..x....',
    '.....xx.....',
    '............',
  ],
  plus: [
    '............',
    '.....xx.....',
    '.....xx.....',
    '.....xx.....',
    '.....xx.....',
    '.xxxxxxxxxx.',
    '.xxxxxxxxxx.',
    '.....xx.....',
    '.....xx.....',
    '.....xx.....',
    '.....xx.....',
    '............',
  ],
  cube: [
    '...xxxxxxxx.',
    '..xoooooooxx',
    '.xoooooooxox',
    'xxxxxxxxxoox',
    'x.......xoox',
    'x.......xoox',
    'x.......xoox',
    'x.......xoox',
    'x.......xox.',
    'x.......xx..',
    'xxxxxxxxx...',
    '............',
  ],
  terrain: [
    '............',
    '............',
    '.......x....',
    '......xxx...',
    '.....xxoxx..',
    '..x.xxoooxx.',
    '.xxxxoooooxx',
    'xxooxoooooox',
    'xoooooooooox',
    'xxxxxxxxxxxx',
    '............',
    '............',
  ],
  compass: [
    '...xxxxxx...',
    '.xx......xx.',
    '.x.......ox.',
    'x.......oox.',
    'x......ooo.x',
    'x.....ox...x',
    'x...xo.....x',
    'x..xxx.....x',
    'x.xxx......x',
    '.xxx......x.',
    '.xx......xx.',
    '...xxxxxx...',
  ],
  tool: [
    '..xxxxxx....',
    '.xoooooox...',
    '.x....xxox..',
    '.......xxox.',
    '......xx.xx.',
    '.....xx...x.',
    '....xx......',
    '...xx.......',
    '..xx........',
    '.xx.........',
    'xx..........',
    '............',
  ],
  help: [
    '...xxxxxx...',
    '..xx....xx..',
    '..xx....xx..',
    '........xx..',
    '......xxx...',
    '.....xx.....',
    '.....xx.....',
    '............',
    '.....xx.....',
    '.....xx.....',
    '............',
    '............',
  ],
  reset: [
    '...xxxxx....',
    '.xx.....xx..',
    '.x.......x..',
    'x.........x.',
    'x.........x.',
    'x......xxxxx',
    'x.......xxx.',
    '.x.......x..',
    '.xx.........',
    '...xxxxx....',
    '............',
    '............',
  ],
  flight: [
    '..........xx',
    '........xxox',
    '......xxooxx',
    '.....xoooxx.',
    '....xooox...',
    '...xooxx....',
    '..xoox......',
    '..xxx.......',
    '.xx.........',
    'xx..........',
    '............',
    '............',
  ],
  leaf: [
    '.......xxxxx',
    '.....xxoooox',
    '...xxoooooox',
    '..xoooooooxx',
    '.xoooooooox.',
    '.xooooooxx..',
    '.xooooxx....',
    '.xxxxx......',
    'xx..........',
    'x...........',
    '............',
    '............',
  ],
  screen: [
    'xxxxxxxxxxxx',
    'xoooooooooox',
    'xoooooooooox',
    'xoooooooooox',
    'xoooooooooox',
    'xoooooooooox',
    'xxxxxxxxxxxx',
    '.....xx.....',
    '...xxxxxx...',
    '............',
    '............',
    '............',
  ],
  link: [
    '......xxxxxx',
    '.........xxx',
    '........xx.x',
    '.......xx..x',
    '......xx....',
    'xxxx.xx.....',
    'x...xx......',
    'x...........',
    'x..........x',
    'x..........x',
    'xxxxxxxxxxxx',
    '............',
  ],
  mouse: [
    '...xxxxxx...',
    '..xoox...x..',
    '..xoox...x..',
    '..xoox...x..',
    '..xxxxxxxx..',
    '..x......x..',
    '..x......x..',
    '..x......x..',
    '..x......x..',
    '...xxxxxx...',
    '............',
    '............',
  ],
  book: [
    '............',
    '.xxxxx.xxxx.',
    'xoooooxoooox',
    'xo.o.oxo.o.x',
    'xoooooxoooox',
    'xo.o.oxo.o.x',
    'xoooooxoooox',
    'xo.o.oxo.o.x',
    'xoooooxoooox',
    '.xxxxxxxxxx.',
    '......xx....',
    '............',
  ],
  heart: [
    '............',
    '.xxx...xxx..',
    'xoooxx.oooox',
    'xoooooxoooox',
    'xoooooooooox',
    '.xoooooooox.',
    '..xoooooox..',
    '...xoooox...',
    '....xoox....',
    '.....xx.....',
    '............',
    '............',
  ],
  phone: [
    '...xxxxxx...',
    '...xoooox...',
    '...xoooox...',
    '...xoooox...',
    '...xoooox...',
    '...xoooox...',
    '...xoooox...',
    '...xoooox...',
    '...xoooox...',
    '...xxxxxx...',
    '...xxooxx...',
    '...xxxxxx...',
  ],
  players: [
    '.ooo........',
    '.ooo...xxx..',
    '.ooo...xxx..',
    '.......xxx..',
    'ooooo.......',
    'ooooo.xxxxx.',
    'ooooo.xxxxx.',
    'ooooo.xxxxx.',
    '.o.o..xxxxx.',
    '.o.o...x.x..',
    '.o.o...x.x..',
    '.......x.x..',
  ],
  keyboard: [
    '............',
    '............',
    'xxxxxxxxxxxx',
    'x.o.o.o.o.ox',
    'xxxxxxxxxxxx',
    'x.o.o.o.o.ox',
    'xxxxxxxxxxxx',
    'x.oooooooo.x',
    'xxxxxxxxxxxx',
    '............',
    '............',
    '............',
  ],
  globe: [
    '...xxxxxx...',
    '.xxoooxx.xx.',
    '.xoooox...x.',
    'xoooox.....x',
    'x.oox...oo.x',
    'x..x...oooox',
    'x......oooox',
    'x.......ooox',
    'x...oo...o.x',
    '.x.oooo...x.',
    '.xx.oo...xx.',
    '...xxxxxx...',
  ],
  sword: [
    '..........xx',
    '.........xox',
    '........xox.',
    '.......xox..',
    '......xox...',
    '..x..xox....',
    '...xxox.....',
    '....xx......',
    '...xxxx.....',
    '..xx..x.....',
    '.xx.........',
    'xx..........',
  ],
};

const svgCache = new Map<string, string>();
function build(name: string): string {
  const grid = GRIDS[name] ?? GRIDS.cube;
  let rects = '';
  grid.forEach((row, y) => {
    // Merge horizontal runs of one colour into a single rect: fewer nodes, no hairline seams.
    let x = 0;
    while (x < row.length) {
      const ch = row[x];
      if (ch !== 'x' && ch !== 'o') {
        x++;
        continue;
      }
      let end = x + 1;
      while (end < row.length && row[end] === ch) end++;
      rects += `<rect x="${x}" y="${y}" width="${end - x}" height="1"${ch === 'o' ? ' opacity=".45"' : ''}/>`;
      x = end;
    }
  });
  return rects;
}
/** Snap a requested size to whole grid pixels, so no pixel is drawn half as wide as its neighbour. */
const snap = (size: number) => (size <= 14 ? 12 : size <= 21 ? 18 : size <= 30 ? 24 : 36);
export const icon = (name: string, size = 20) => {
  let rects = svgCache.get(name);
  if (rects === undefined) {
    rects = build(name);
    svgCache.set(name, rects);
  }
  const px = snap(size);
  return `<svg class="px-icon" width="${px}" height="${px}" viewBox="0 0 12 12" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true">${rects}</svg>`;
};
/** The logo: a grass block in three pixel faces. */
export const logo = `<svg class="logo-block" width="36" height="36" viewBox="0 0 12 12" shape-rendering="crispEdges" aria-hidden="true"><path d="M6 0h1v1h2v1h2v1h1v1h-2v1H8v1H7v1H5V6H4V5H2V4H0V3h1V2h2V1h2V0z" fill="#8fc45a"/><path d="M5 1h2v1h2v1H7v1H5V3H3V2h2z" fill="#b5e07a"/><path d="M0 4h2v1h2v1h1v1h1v5H5v-1H3v-1H1V9H0z" fill="#8a5a36"/><path d="M0 4h2v1h2v1h1v1h1v1H5V7H3V6H1V5H0z" fill="#6fa644"/><path d="M6 7h1V6h1V5h2V4h2v5h-1v1H9v1H7v1H6z" fill="#6b4428"/><path d="M6 7h1V6h1V5h2V4h2v1h-2v1H8v1H7v1H6z" fill="#5a8f38"/><path d="M1 7h1v1H1zM3 9h1v1H3zM8 8h1v1H8zM10 6h1v1h-1z" fill="#5c3b22"/></svg>`;
